# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
# assistant_id: 20240306-133721-right-cayenne

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# See https://rasa.com/docs/rasa/tuning-your-model for more information.

# pip install spacy
# python -m spacy download en_core_web_sm
- name: SpacyNLP
  model: en_core_web_md

# tokenization
# - name: WhitespaceTokenizer
- name: SpacyTokenizer

# featurization
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4

# entity extraction
- name: SpacyEntityExtractor
# - name: CRFEntityExtractor
- name: DIETClassifier   # for entity extraction
  epochs: 100
  constrain_similarities: true

# response selection
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true

# fallback
- name: FallbackClassifier
  threshold: 0.3   # confidence level
  ambiguity_threshold: 0.1

# ducklingEntityExtractor
- name: DucklingEntityExtractor
  # url of the running duckling server
  url: "http://localhost:8000"
  # dimensions to extract
  dimensions: ["time"]
  locale: "En_IN"
  timezone: "India Standard Time"
  timeout : 10

# synonym mapper
- name: EntitySynonymMapper

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# No configuration for policies was provided. The following default policies were used to train your model.
# If you'd like to customize them, uncomment and adjust the policies.
# See https://rasa.com/docs/rasa/policies for more information.
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
assistant_id: 20240312-110309-merry-hook
