import pandas as pd
def get_ticker_mapping(): 
    df = pd.read_excel('stock_data/stock_tickers.xlsx')
    # Create a mapping dictionary from the DataFrame
    ticker_mapping = dict(zip(df['Company Name'].str.lower(), df['Symbol']))
    return ticker_mapping
#     return {
#         "tesla": "TSLA",
#         "apple": "AAPL",
#         "microsoft": "MSFT",
#         "google": "GOOGL",
#         "amazon": "AMZN",
#         "facebook": "META",
#         "twitter": "TWTR",
#         "netflix": "NFLX",
#         "instagram": "FB",
#         "snapchat": "SNAP",
#         "uber": "UBER",
#         "lyft": "LYFT",
#         "disney": "DIS",
#         "walmart": "WMT",
#         "nike": "NKE",
#         "coca-cola": "KO",
#         "pepsi": "PEP",
#         "mastercard": "MA",
#         "visa": "V",
#         "johnson & johnson": "JNJ",
#         "nvidia": "NVDA",
#         "intel": "INTC",
#         "amd": "AMD",
#         "oracle": "ORCL",
#         "ibm": "IBM",
#         "cvs": "CVS",
#         "atlassian": "TEAM",
#         "goldman sachs": "GS",
#         "adobe": "ADBE",
#         "home depot": "HD",
#         "ebay": "EBAY",
#         "the clorox company": "CLX",
#         "procter & gamble": "PG",
#         "dupin ampharme": "DUPFR",
#         "nordstrom": "NST",
#         "costco wholesale corporation": "COST",
#         "target corporation": "TGT",
#         "walmart digital": "WDCGY",
#         "seagate technology": "STX",
#         "sony": "SONY",
#         "samsung": "SAMS",
#         "one plus": "ONEPL",
#         "nintendo": "NINT",
#         "sony entertainment entertainment": "SNE",
#         "oppo": "OPPO"
# }
